Alter env var structure
DEFRA/rod-licensing pull request #1045
Opened 2022-01-26 11:18 UTC by ScottDormand96

https://eaflood.atlassian.net/browse/IWTF-2663?atlOrigin=eyJpIjoiYzE1NDQ1NDc4Nzc3NDdjMTljNDg4YzZjMGI0NjYzNjUiLCJwIjoiaiJ9

Change how hold env variables so added to gitignore so not longer part of git repo

2022-01-28 12:04 UTC, nabeelamir-defra requested changes
It doesn't say in the story, but I think it's important to do. The README in the docker file should be updated the reflect these changes

2022-02-03 11:48 UTC, jaucourt requested changes
This looks good, but it does need the instructions in README.env to be amended

2022-02-03 13:16 UTC, ScottDormand96 commented
> This looks good, but it does need the instructions in README.env to be amended

I made changes to the README within the docker folder

2022-02-04 13:42 UTC, jaucourt requested changes
Sorry, few more changes needed

2022-02-04 13:42 UTC, jaucourt commented on docker/README.md
> +```
You don't want to do `git mv` as that'd rename them within git. `cp fulfilment_job.env.example .fulfilment_job.env`, etc, would do what's needed as we want to keep the original

2022-02-04 13:42 UTC, jaucourt commented on docker/README.md
> +In order to run the services locally, you'll need to to rename the env files in the in the [env](env) folder to include a leading dot and removing .example. You'll need to insert the appropriate valu
This isn't quite correct: 'Either rename as below or grab the filles from the the gitlab repository: fish/rod-licensing-env-vars' should be something like 'Copy files as follows, then get values for secret files from gitlab repo fish/rod-licensing-env-vars.'

2022-02-04 13:42 UTC, jaucourt commented on .gitignore
> +*.env
Thinking about it, we won't need this as we're already ignoring files starting with a dot, above

2022-02-04 15:30 UTC, jaucourt approved these changes

2022-02-04 15:33 UTC, nabeelamir-defra approved these changes

2022-02-04 15:49 UTC, merged