Multibuy - maintain person data
DEFRA/rod-licensing pull request #1172
Opened 2022-03-29 13:17 UTC by ScottDormand96

https://eaflood.atlassian.net/browse/IWTF-2771

When adding another licence personal information (for example name) doesnt need to be input again

2022-03-31 10:49 UTC, nabeelamir-defra commented on packages/gafl-webapp-service/src/handlers/multibuy-handler.js
> +export const CheckMultibuyForYou = async request => {
this should be camel case, so checkMultibuyForYou.

2022-03-31 10:54 UTC, nabeelamir-defra commented on packages/gafl-webapp-service/src/pages/licence-details/licence-for/result-function.js
> +    return Multibuy.YES
Perhaps this Multibuy.YES should be MultibuyForYou.YES. To me Multibuy.YES implies that it is multibuy for you or someone else.

2022-03-31 13:12 UTC, jaucourt requested changes
Few changes needed here guys, as you were expecting. I probably haven't caught everything, but I'll re-review once you've done the first refactor

2022-04-04 10:23 UTC, jaucourt requested changes
Sorry, but a few more changes are needed

2022-04-04 10:23 UTC, jaucourt commented on packages/gafl-webapp-service/src/pages/contact/digital-licence/licence-fulfilment/__tests__/result-function.spec.js
> +  }
You should mock out isMultibuyForYou rather than the request, otherwise you're testing isMultibuyForYou again

2022-04-04 10:23 UTC, jaucourt commented on packages/gafl-webapp-service/src/pages/licence-details/licence-for/__tests__/result-function.spec.js
> +    })
Again, I think these would be simpler if you mocked out `isMultibuyForYou`

2022-04-07 10:23 UTC, jaucourt approved these changes

2022-04-07 13:22 UTC, merged