Accessibility - Selected licences title
DEFRA/rod-licensing pull request #1466
Opened 2022-09-08 14:54 UTC by ScottDormand96

https://eaflood.atlassian.net/browse/IWTF-3003

Update title on selected licences page

2022-09-08 15:21 UTC, irisfaraway commented
@ScottDormand96 Does this also fix the missing title attribute mentioned on Jira or is that a separate PR?

2022-09-12 15:55 UTC, jaucourt requested changes
Looks fine, but if you could include the new label that'd be great. If it's more work than adding a label, we can create a fresh ticket for the it.

2022-09-12 15:55 UTC, jaucourt commented on packages/gafl-webapp-service/src/pages/multibuy/view-licences/view-licences.njk
> +        <h1 class="govuk-heading-l">Selected licences</h1>
This has been missed when we were moving all hardcoded strings to be labels. Please could you add a new label in en.json and cy.json, then replace the text here with that new label?

2022-09-13 07:57 UTC, jaucourt approved these changes

2022-09-13 14:57 UTC, merged