analytics banner only /buy
DEFRA/rod-licensing pull request #1477
Opened 2022-09-15 14:36 UTC by ScottDormand96

https://eaflood.atlassian.net/browse/IWTF-3075

Only display analytics banner when uri begins with /buy

2022-09-15 15:48 UTC, irisfaraway submitted a review, later dismissed

2022-09-15 15:48 UTC, irisfaraway commented on packages/gafl-webapp-service/src/handlers/page-handler.js
> +    if (request.path.startsWith('/buy')) {
Could we add a test for this?

2022-09-16 08:01 UTC, jaucourt requested changes

2022-09-16 08:01 UTC, jaucourt commented on packages/gafl-webapp-service/src/handlers/page-handler.js
> +    }
This would be more concise if you did 
```
pageData.displayAnalytics = request.path.startsWith('/buy')
```

2022-09-16 08:29 UTC, jaucourt approved these changes

2022-09-16 09:33 UTC, merged