Welsh translation - error page
DEFRA/rod-licensing pull request #1501
Opened 2022-10-10 13:41 UTC by ScottDormand96

https://eaflood.atlassian.net/browse/IWTF-2986

Update the error page to include welsh translations

2022-10-13 14:14 UTC, jaucourt requested changes

2022-10-13 14:14 UTC, jaucourt commented on packages/gafl-webapp-service/src/locales/cy.json
>    "client_error_content_try_another": "try to get back to your application",
I think we need a translation for this too - particularly given that the first part of the sentence will no longer be in English, so we'd have "Gallwch try to get back to your application"

2022-10-14 09:08 UTC, MickStein approved these changes

2022-10-19 08:12 UTC, jaucourt approved these changes

2022-10-19 08:34 UTC, merged