Multibuy - delete licence page
DEFRA/rod-licensing pull request #1595
Opened 2023-01-04 11:58 UTC by ScottDormand96

https://eaflood.atlassian.net/browse/IWTF-3191

Page to confirm whether to remove a licence

2023-01-11 10:19 UTC, MickStein requested changes

2023-01-11 10:19 UTC, MickStein commented on packages/gafl-webapp-service/src/pages/multibuy/remove-licence/__tests__/route.spec.js
> +  const mockRequest = createMockRequest({
Should we be using this createMockRequest function? I'm concerned about readability and inconsistency of this not being done throughout. Might be one to discuss in a 3 amigos?

2023-01-11 10:19 UTC, MickStein commented on packages/gafl-webapp-service/src/pages/multibuy/remove-licence/__tests__/update-transaction.spec.js
> +const set = jest.fn()
Can't this be added to createMockRequest?

2023-01-12 11:02 UTC, jaucourt requested changes

2023-01-18 15:15 UTC, jaucourt requested changes

2023-01-18 15:15 UTC, jaucourt commented on packages/gafl-webapp-service/src/pages/multibuy/remove-licence/__tests__/update-transaction.spec.js
> +    const mockRequest = createRequestMock(transaction, getPermissionTwo())
You're reusing these in different tests - fresh test, fresh mocks.

Also, don't presume that `getPermissionTwo() === getPermissionTwo()`. You should be doing something like this instead:
```
const permissionToRemove = getPermissionTwo()
const transaction = { permissions: [getPermissionOne(), permissionToRemove, getPermissionThree()] }
const mockRequest = createRequestMock(transaction, permissionToRemove)
```

2023-01-18 15:15 UTC, jaucourt commented on packages/gafl-webapp-service/src/pages/multibuy/remove-licence/__tests__/update-transaction.spec.js
> +    })
Rather than these three tests, just check that the remaining permissions don't include the permission that you removed.

2023-01-19 10:10 UTC, jaucourt approved these changes

2023-01-19 10:53 UTC, MickStein approved these changes

2023-01-20 09:35 UTC, merged