Add price increase notification banner text
DEFRA/rod-licensing pull request #1627
Opened 2023-02-06 14:04 UTC by irisfaraway

https://eaflood.atlassian.net/browse/IWTF-3242

We want to tell users about the price change before they reach payment so they can make an informed decision.

2023-02-07 14:52 UTC, jaucourt requested changes
Just one thing to look at, but given you branched off my new prices page branch, you may have to manually marge in develop too.

2023-02-07 15:44 UTC, irisfaraway commented on packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/route.spec.js
> +      mockTransactionCacheGet.mockImplementationOnce(() => ({ isLicenceForYou: true }))
@jaucourt Refactored!

2023-02-07 15:55 UTC, irisfaraway commented on packages/gafl-webapp-service/src/pages/licence-details/licence-to-start/__tests__/route.spec.js
> +      mockTransactionCacheGet.mockImplementationOnce(() => ({ isLicenceForYou: true }))
I've also now rebased so merging should be alright.

2023-02-08 09:35 UTC, jaucourt approved these changes

2023-02-09 09:54 UTC, merged