Refund policy welsh
DEFRA/rod-licensing pull request #1660
Opened 2023-03-15 15:39 UTC by ScottDormand96

https://eaflood.atlassian.net/browse/IWTF-3294

Update refund policy page with welsh translation

2023-03-16 16:05 UTC, irisfaraway requested changes

2023-03-16 16:05 UTC, irisfaraway commented on packages/gafl-webapp-service/src/locales/cy.json
>    "refund_bulletpoint_1_1": "Gall Asiantaeth yr Amgylchedd ad-dalu cost trwydded i’r prynwr yn unig. Dylai’r holl geisiadau am ad-daliad gael eu cyfeirio i Asiantaeth yr Amgylchedd, ac eithrio mewn a
Think this line needs to be updated

2023-03-20 08:29 UTC, irisfaraway approved these changes

2023-03-20 09:43 UTC, jaucourt approved these changes

2023-03-21 14:04 UTC, merged