Display catch return info if any salmon licences are purchased
DEFRA/rod-licensing pull request #1670
Opened 2023-03-30 12:57 UTC by irisfaraway

https://eaflood.atlassian.net/browse/IWTF-3316

This fixes a bug in multibuy where we were only displaying the catch return info on the order complete page if the most recently added licence was for salmon fishing.

This info should be displayed if any of the licences added are for salmon fishing, not just the latest one.

2023-03-30 12:58 UTC, irisfaraway commented
Also I refactored a bunch of tests to reduce duplication (couldn't help myself)

2023-03-30 13:06 UTC, irisfaraway commented
Do not review/merge for now – will revisit after https://github.com/DEFRA/rod-licensing/pull/1668 is done

2023-04-06 17:14 UTC, irisfaraway commented
Now ready to review. Still includes the test refactor to try to simplify the tests and make them more consistent. Also removes some accidental cruft from the order-complete page.

2023-04-17 15:26 UTC, jaucourt requested changes

2023-04-18 16:19 UTC, irisfaraway commented on packages/gafl-webapp-service/src/pages/order-complete/order-complete/route.js
> +  return false
Very nice, I did not know that existed! Thanks 👍

2023-04-19 11:00 UTC, jaucourt approved these changes

2023-04-19 11:04 UTC, jaucourt commented on packages/gafl-webapp-service/src/pages/order-complete/order-complete/__tests__/order-complete.spec.js
> -  },
I've approved, but you've reduced the quality of the tests and reinforced the coupling between constants and the order complete getData function by removing this mocking. It's not a massive danger, as I doubt we're going to ever remove that, but that's why I did this.

2023-04-20 09:00 UTC, merged