Over 66 content
DEFRA/rod-licensing pull request #1741
Opened 2023-06-29 15:23 UTC by ScottDormand96

https://eaflood.atlassian.net/browse/IWTF-3537

Updating the content for when over 66 is referenced

2023-07-10 13:24 UTC, irisfaraway approved these changes

2023-07-12 10:06 UTC, jaucourt requested changes
Nice work, just one small change, please

2023-07-12 10:06 UTC, jaucourt commented on packages/gafl-webapp-service/src/processors/licence-type-display.js
> +    typesStrArr.push(', ')
This should be part of the label, rather than being added as a hard-coded string

2023-07-12 13:33 UTC, jaucourt approved these changes

2023-07-12 13:37 UTC, merged