Update English language version of accessibility statement
DEFRA/rod-licensing pull request #1752
Opened 2023-07-10 11:34 UTC by irisfaraway

https://eaflood.atlassian.net/browse/IWTF-3055

This PR makes some modifications to the English language version of the accessibility statement as documented on Jira.

2023-07-11 10:54 UTC, irisfaraway commented
For whoever reviews this – there were some inconsistencies in the text so might be worth checking the comments on Jira for an explanation.

Also it may be easier to review by looking at the page itself so deploy the `iwtf-3053-accessibility-statement-updates` tag if you want to do that :)

2023-07-12 09:42 UTC, jaucourt requested changes

2023-07-12 09:42 UTC, jaucourt commented on packages/gafl-webapp-service/src/locales/en.json
> +  "access_statement_ability_net_1": "",
Should we just get rid of this, rather than having an empty label?

2023-07-12 09:59 UTC, jaucourt approved these changes

2023-07-13 09:50 UTC, merged