Initial setup RP job
DEFRA/rod-licensing pull request #1769
Opened 2023-08-09 07:05 UTC by ScottDormand96

https://eaflood.atlassian.net/browse/IWTF-3381

Setup recurring payment job

2023-08-14 10:11 UTC, irisfaraway requested changes
Looks good, just a few little things to maybe tweak.

Also just wondering as the AC says we should be able to successfully run the job – do we need to have it outputting a line to the console or something just so we have something to test?

2023-08-14 10:11 UTC, irisfaraway commented on README.md
> +- [recurring-payments-job](packages/recurring-payments-job/README.md)
Can we also have a line of description of what the job does, like the others do above?

2023-08-15 15:45 UTC, jaucourt commented on packages/recurring-payments-job/LICENSE
> +Copyright (c) 2020 DEFRA
Let's check with a Principal Dev on this

2023-08-16 11:47 UTC, ScottDormand96 commented on packages/recurring-payments-job/LICENSE
> +Copyright (c) 2020 DEFRA
I will message Ben

2023-09-18 06:48 UTC, merged