Ensuring page titles meet WCAG 2.1 criteria
DEFRA/rod-licensing pull request #1940
Opened 2024-03-26 11:14 UTC by lailien3

https://eaflood.atlassian.net/browse/IWTF-3824

A recent accessibility assessment identified a number of issues. This ticket is to make the Page titles meet the criteria of the WCAG 2.1 criteria. The issue and suggested solution is detailed on page 91-93 of the DAC assessment. On the ‘Who is this fishing licence for?’ page, the page title does not follow the GOV.UK Design System page title recommendations; including "Get a rod fishing licence" helps screen reader users, who are dependent on having unique and accurate page titles to orientate themselves within the service.

2024-03-26 15:42 UTC, jaucourt requested changes
This has several instances of a merge error too - I'm pretty sure you don't want to remove the work you did on the pageTitle macro?

2024-03-26 15:42 UTC, jaucourt commented on packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
> +{% block pageTitle %}{{ title }}{{ mssgs.header_service_name_title }}{{ mssgs.gov_uk }}{% endblock %}
merge error

2024-03-27 09:00 UTC, lailien3 commented on packages/gafl-webapp-service/src/pages/contact/address/lookup/address-lookup.njk
> +{% block pageTitle %}{{ title }}{{ mssgs.header_service_name_title }}{{ mssgs.gov_uk }}{% endblock %}
Correct, my mistake

2024-03-27 09:27 UTC, jaucourt approved these changes

2024-03-27 12:05 UTC, jaucourt approved these changes

2024-03-27 12:11 UTC, merged