Easy renewal query
DEFRA/rod-licensing pull request #2080
Opened 2024-11-18 10:24 UTC by ScottDormand96

https://eaflood.atlassian.net/browse/IWTF-3155

Implement amendments to the Easy Renewal query to improve performance

2024-12-11 12:48 UTC, jaucourt requested changes
I've put a few comments inline, but also there's a lot of use of `let` rather than `const`. I've highlighted a couple, but there shouldn't be any - I appreciate in general you're modifying existing code, but this is a clear improvement that would be fairly easy to make. Thanks!

2024-12-11 12:48 UTC, jaucourt commented on packages/sales-api-service/src/schema/authenticate.schema.js
> +const referenceLength = 6
By convention, we use `ALL_CAPS_WITH_UNDERSCORES` for constant values like this, so change to `REFERENCE_LENGTH`, please

2024-12-16 13:59 UTC, ScottDormand96 commented on packages/dynamics-lib/src/queries/__tests__/permission.queries.spec.js
> +        filter: "defra_name eq 'ABC123' and statecode eq 0",
in predefined query we strip the entity out so test is a Contact fails but can test the property returned  is defer_ContactId
------
let me know if above makes sense or we can have quick chat

2025-01-16 08:48 UTC, ScottDormand96 commented on packages/dynamics-lib/src/queries/__tests__/permission.queries.spec.js
> +        filter: "(defra_ContactId/contactid eq '12345') and statecode eq 0",
this doesn't work with Contact, the entity isn't present. When log value of query get:
`[
      { property: 'defra_ContactId' },
      { property: 'defra_PermitId' },
      {
        property: 'defra_defra_permission_defra_concessionproof_PermissionId',
        expand: [ [Object] ]
      }
    ]`

2025-01-20 16:10 UTC, jaucourt approved these changes

2025-01-31 13:54 UTC, merged