Create RP Record in CRM
DEFRA/rod-licensing pull request #2081
Opened 2024-11-21 17:10 UTC by jaucourt

https://eaflood.atlassian.net/browse/IWTF-4262

After a successful payment, when the permission is provisioned, a RCP record should be created along with everything else. It shouldn't be created if the RCP toggle is off

2024-12-09 15:29 UTC, jaucourt commented on packages/sales-api-service/src/services/__tests__/recurring-payments.service.spec.js
> +    it.each([
Good reminder, I'd meant to add these but then forgot

2024-12-09 15:32 UTC, jaucourt commented on packages/dynamics-lib/src/entities/recurring-payment.entity.js
> -
It shouldn't do, the link is still set up. I think they were added due to a misunderstanding of how these entities work. Plus, no tests failed other than the ones in recurring-payment.entity.spec.js

2024-12-10 09:29 UTC, irisfaraway requested changes

2024-12-10 09:29 UTC, irisfaraway commented on packages/sales-api-service/src/services/__tests__/recurring-payments.service.spec.js
> +        "issued on 30th March '25 at 1am, starts at 1:30am - next due on 20th March '26",
I'd suggest testing this for 12:30am 1st of April instead, as 1am on 30 March 2025 is precisely when BST starts and so technically immediately skips to 2am. Also if we test at 12:30 then we will land in the window where it's one date in BST and another date in UTC, which I think is worth testing.

2024-12-10 09:36 UTC, irisfaraway approved these changes

2024-12-10 09:39 UTC, merged