Ensure CRM flag sets to Postal Fulfilment for Direct Debit & Post Off…
DEFRA/rod-licensing pull request #687
Opened 2021-05-07 09:59 UTC by nabeelamir-defra

…ice customers

https://eaflood.atlassian.net/browse/IWTF-1972

Ensure CRM flag sets to Postal Fulfilment for Direct Debit & Post Office customers if the permit can be posted

2021-05-07 12:45 UTC, DGajewska approved these changes

2021-05-10 12:53 UTC, jaucourt requested changes

2021-05-10 12:53 UTC, jaucourt commented on packages/pocl-job/src/transform/bindings/pocl/transaction/__tests__/__snapshots__/transaction.bindings.spec.js.snap
> -          "postalFulfilment": true,
I think we need a variety here (some records with postalFulfilment set to true)

2021-05-10 12:53 UTC, jaucourt commented on packages/pocl-job/src/transform/bindings/pocl/transaction/__tests__/transaction.bindings.spec.js
> +      (acc, m) => ({ ...acc, [m]: { find: jest.fn(() => ({ id: `${m}-id`, isForFulfilment: false })) } }),
See previous comment

2021-05-10 14:20 UTC, merged