Fix: Only pass street name to GovPay if provided
DEFRA/rod-licensing pull request #731
Opened 2021-06-02 15:09 UTC by DGajewska

IWTF-2170

* Adds conditonal logic to prefilled billing address
* Adds tests for payment.js

2021-06-02 15:31 UTC, jaucourt requested changes
It's great that you've added in quite a few new tests that cover more than the new code you've added, thanks for doing that. I've made a couple of suggestions to broaden tests to be a little more expressive, this could be done with most of your tests, as at the moment the tests could be passed by simply hardcoding values. This probably wouldn't ever happen, but it would make them slightly more expressive and easy to understand, as well as allowing edge cases to be tested.

2021-06-02 15:31 UTC, jaucourt commented on packages/gafl-webapp-service/src/processors/__tests__/payment.spec.js
> +      expect(result.return_url).toBe('https://localhost:1234/buy/agreed')
After looking for a bit, I can see that `result.return_url` should be the same as ` ``http://${request.info.host}/buy/agreed`` `, however a bit more of a thorough test would be a bit more descriptive. If you were to modify the `createRequest` method to allow for host to be specified, but default to `localhost:1234`, you could then do something like:
```
['localhost:4321', 'otherhost:8888', 'samplehost:4444'].forEach(host => 
  it(`uses SSL when 'x-forwarded-proto' header is present, host '${host}'`, () => {
    const request = createRequest(host)
    expect(result.return_url).toBe(`https://${host}/buy/agreed`)
  })
)
```

2021-06-02 15:31 UTC, jaucourt commented on packages/gafl-webapp-service/src/processors/__tests__/payment.spec.js
> +      expect(result.return_url).toBe('http://localhost:1234/buy/agreed')
Same here, but use a different list to previously

2021-06-02 15:40 UTC, nabeelamir-defra approved these changes

2021-06-03 11:12 UTC, jaucourt approved these changes

2021-06-03 12:03 UTC, merged